name: Bug Report
description: Something isn't working
labels: [bug]
body:
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What actually happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Run `npm start`
        2. Type "..."
        3. See error
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: npm show ntox version
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node.js Version
      placeholder: node --version
    validations:
      required: false